version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "MEDPLUM_BASE_URL=https://devapi.medplum.lotuscares.ai/" >> .env
  pre_build:
    commands:
      - npm install
      - npm install -g rimraf
      - npm install -g typescript
      - npm install -g jest
      - npm install --save-dev @types/jest
  build:
    commands:
      - echo "MEDPLUM_BASE_URL=https://devapi.medplum.lotuscares.ai/" >> packages/app/.env.defaults
      - npm run build -- --filter=@medplum/app
      - cp -r packages/app/dist ./app-dist
  post_build:
    commands:
      - aws s3 sync app-dist s3://lotus-medplum-app-bucket-dev
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
